name: Mirror sync
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
env:
  GITHUB_REPO_NAME: <your-github-repo>
  GITEE_DIR_NAME: <your giteee repo>-<branch>
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Down load gitee source
        run: |
          wget https://gitee.com/api/v5/repos/<your_name>/<your-repo>/zipball?access_token=${{ secrets.GITEE_ACCESS_TOKEN }} -O <branch>.zip
          unzip <branch>.zip
          cp $GITEE_DIR_NAME/* . -r
          rm $GITEE_DIR_NAME <branch>.zip -rf
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          default_author: github_actor
          fetch: false
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          pathspec_error_handling: ignore